### ISSUE TITLE
version change

### ISSUE THREAD

**Issue by tomasMikulak** [gandalf3/auto-reload-linked-libraries#6] opened 2024-09-12 16:04 UTC
Hi, I am trying to solve problem with linked library reload, but to another file, _v001.blend to _v002.blend, hopefully with same structure, main collection keeps name. But I can no t get same functinality as outliner right click relocate function. Any idea?
thanks, tomas

**Comment by kitt-cat** [comment] 2024-09-13 19:04
Hi, I'm not sure I follow.. But I'd be happy to take a look, would it be possible to upload a pair of example files (don't need the full content, just enough to demo the issue) and describe the steps you're performing plus expected vs observed behavior?

**Comment by tomasMikulak** [comment] 2024-09-13 20:59
Hi,
sure, I will try to provide some asset examples and my tool setup.
thanks,
tomas

pi 13. 9. 2024 o 21:05 gandalf3 ***@***.***> napísal(a):

**Comment by tomasMikulak** [comment] 2024-09-17 18:27
[blender_update_test.zip](https://github.com/user-attachments/files/17033209/blender_update_test.zip)

Hi,
I am sending packed files, there is SCENE_test_v001.blen, that has 2 assets referenced, a cube and a sphere, both v001. folder with v001 also contains v002. there is also my addon, it should be found in develeopment section in blender addons. It has 3 buttons( those we need to focus on). update assets, it updates all scene assets if greater version is available. under it there are 2 other. it works the way, that you select a mesh o particuler asset and you could go versin down or up if there is some issue. Now, the final version of update assets is set the way that it also saves and reopens the scene, what I think is nonsense. but so far only working process. version change buttons, don't save what makes them not fully fulfill the task of updating now. I suggest you save test file to some other name, because after update it will resave it. with updated assets. main definitions in addon would be updateAssets(), updateOneAsset(), rest of the functions deliver I think fine results to process. and also classes WM_OT_assetUpdate, WM_OT_assetUpdate_lower, WM_OT_assetUpdate_upper, If any questions, just ask. 

tomas

**Comment by tomasMikulak** [comment] 2024-09-17 18:27
we use blender 3.6.12

**Comment by kitt-cat** [comment] 2024-09-17 23:43
Thanks for the demo and explanation! I'm not sure I understand where auto-reload-linked-libraries fits into your workflow. However I do see that when I click update_assets, my addon throws this exception:

```python
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "auto_reload_libraries/extern/watchdog/observers/api.py", line 204, in run
    self.dispatch_events(self.event_queue)
  File "auto_reload_libraries/extern/watchdog/observers/api.py", line 380, in dispatch_events
    handler.dispatch(event)
  File "auto_reload_libraries/extern/watchdog/events.py", line 275, in dispatch
    self.on_any_event(event)
  File "auto_reload_libraries/__init__.py", line 81, in on_any_event
    self.func()
  File "auto_reload_libraries/__init__.py", line 107, in call_callbacks
    for cb in self.watched_directories[self.directory]:
              ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'blender_update_test/PR_CUBE/publish'
```

Is that the case for you too? I will try to track down the cause

**Comment by tomasMikulak** [comment] 2024-09-18 04:20
try to set paths to full paths, but it should work anyway. we are on python
2.7.18, that might be also some syntax issue you get

**Comment by kitt-cat** [comment] 2024-09-18 09:01
..wait how are you on python 2.7? I thought blender 3.6 was bundled with python 3.10? I'm pretty sure my addon won't run in any python 2.x interpreter \*super confused*

I committed a fix for the KeyError exception but it was a ultimately inconsequential, it was just happening during file reload and resolved itself right away..so I'm guessing that wasn't your issue. I'm sorry I'm still entirely lost as to what the issue with auto-reload-linked-libraries is, and its starting to sound to me like you're looking for help debugging your own addon? If so that's fine but I'm really not the best resource, I wrote this addon years ago and am not readily familiar with more recent changes to the API..

My addon [uses the `wm.lib_reload` operator](https://github.com/gandalf3/auto-reload-linked-libraries/blob/master/__init__.py#L193) to do the library reloading. Perhaps using it might be a way around the issues you're running into using the outliner methods? If that doesn't help [blender.stackexchange.com](https://blender.stackexchange.com/) or [another support community](https://www.blender.org/community/) may be able to assist further. I'm closing this issue since it does not appear to be about auto-reload-linked-libraries anymore but my apologies if I've misunderstood, please do let me know if there is anything related to my addon!

**Closed as completed by kitt-cat** 2024-09-18 09:01 UTC

**Comment by tomasMikulak** [comment] 2024-09-21 19:47
Hi,
sure I need to work on my addon, it doesn't matter if it is addon or not, I
just can't make this process run with python, just in ui and you were the
only one I found who dealt with similar topics. I don't really understand
how python in system could make issue with python in Blender, but I write
code in scripting tab and test it in ui and then save  it to file, so I
don't mind when it works how it works. You think of update only in there is
new save of same file, but my need it to swap linked file with another save
of same asset, because I checked and found there is new version. I probably
was supposed to only work on you project, sorry. I just didn't know how
other way to contact you about my problem,
take care,
tomas

st 18. 9. 2024 o 11:02 gandalf3 ***@***.***> napísal(a):

**Comment by kitt-cat** [comment] 2024-09-23 08:57
No worries! I'd normally be happy to help troubleshoot your addon in depth but I'm just too busy to volunteer for that at the moment..(forgive me) I'm not too familiar with the asset library system introduced a few versions ago.. I thought my addon would handle asset libraries out of the box but to be honest I have not tested it; if you were expecting your use case to be satisfied by my addon/my addon isn't handling asset libraries as one would hope, please let me know I do feel that reloading linked assets when their source file is updated is absolutely within the scope of my addon and I'd be interested in fixing that.

Regardless, if I am understanding correctly and the issue you're experiencing is mostly about triggering library reloading from python not working, I'd definitely suggest giving the  [`wm.lib_reload`](https://docs.blender.org/api/current/bpy.ops.wm.html#bpy.ops.wm.lib_reload) operator a try, though figuring out how to call blender's operators can be a bit unintuitive; [this stackexchange answer](https://blender.stackexchange.com/a/6105) has some good tips and my addon has [a working example for `wm.lib_reload` specifically, here](https://github.com/gandalf3/auto-reload-linked-libraries/blob/master/__init__.py#L193).
